repos:
- repo: local
  hooks:
  - id: validate-filenames
    name: validate-filenames
    entry: python scripts/validate-filenames.py
    language: python
    types: [jupyter]
    exclude: ^templates/
    additional_dependencies: [requests]
- repo: local
  hooks:
  - id: validate-urls
    name: validate-urls
    entry: python scripts/validate-urls.py
    language: python
    types: [jupyter]
    additional_dependencies: [nbformat, requests]
