#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title: eqcbook                         # The title of the book. Will be placed in the left navbar.
author: the Copernicus Climate Change Service (C3S), entrusted to ECMWF (European Centre for Medium-Range Weather Forecasts)                        # The author of the book
copyright: "2024"                     # Copyright year to be placed in the footer
logo: C3S–POS–LINE.png                          # A path to the book logo

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")

# Information about where the book exists on the web
repository:
  url: https://github.com/ecmwf-projects/c3s_eqc_book_main  # Online location of your book
  path_to_book: /c3s_eqc_quality_assesments# Optional path to your book, relative to the repository root
  # branch:  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  announcement: "⚠️This is under development!⚠️"

# Parse and render settings
parse:
  myst_enable_extensions:  # default extensions to enable in the myst parser. See https://myst-parser.readthedocs.io/en/latest/using/syntax-optional.html
    # - amsmath
  - colon_fence
    # - deflist
  - dollarmath
  - html_admonition
  - html_image
  - linkify
    # - replacements
    # - smartquotes
  - substitution
  - tasklist
  myst_url_schemes: [mailto, http, https] # URI schemes that will be recognised as external URLs in Markdown links
  myst_dmath_double_inline: true  # Allow display math ($$) within an inline context



# Do not include these files in the build
# exclude_patterns: [content.md, "**.ipynb_checkpoints", "**README.md"]
only_build_toc_files: true

# Sphinx
sphinx:
  config:
    suppress_warnings: ["etoc.glob"]

#######################################################################################
# Launch button settings
#launch_buttons:
#  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
#  binderhub_url             : "https://mybinder.org" # The URL of the BinderHub (e.g., https://mybinder.org or https://binder.pangeo.io, https://aws-uswest2-binder.pangeo.io)

# search_bar_position: left

