[dependency-groups]
check-links = [
  "pytest>=8.4.2",
  "pytest-check-links[cache]>=0.10.1",
  "requests>=2.34.2"
]
dev = [
  "pre-commit>=4.6.1"
]

[project]
dependencies = []
description = "C3S2 EQC Quality Assessment"
name = "c3s2-eqc-quality-assessment"
readme = "README.md"
requires-python = ">=3.14"
version = "0.1.0"

[tool.pytest.ini_options]
addopts = [
  "-vv",
  "--check-links",
  "--check-anchors",
  "--check-links-ignore=^(?!https?://)|^https?://doi\\.org/",
  "--check-links-cache",
  "--check-links-cache-expire-after=86400",
  "--check-links-cache-backend-opt=allowable_codes:[200,403]",
  # Known 403s
  "--check-links-ignore=https://www.volkskrant.nl/wetenschap/~b301f81f2/",
  "--check-links-ignore=https://glisa.umich.edu/lake-superior-retrospective/",
  "--check-links-ignore=https://psycnet.apa.org/record/1948-15040-000",
  "--check-links-ignore=https://sealevel.nasa.gov/understanding-sea-level/global-sea-level/overview/",
  "--check-links-ignore=https://earthobservatory.nasa.gov/images/148414/lake-victorias-rising-waters",
  "--check-links-ignore=https://timesofmalta.com/article/february-marks-9th-straight-month-recordsmashing-global-heat.1087990"
]

[tool.ruff]
indent-width = 4
# Same as Black.
line-length = 88

[tool.ruff.lint]
ignore = [
  # pydocstyle: Missing Docstrings
  "D1"
]
select = [
  # pyflakes
  "F",
  # pycodestyle
  "E",
  "W",
  # isort
  "I",
  # pydocstyle
  "D"
]

[tool.ruff.lint.pycodestyle]
max-line-length = 110

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.uv]
package = false
