# Same as Black.

indent-width = 4
line-length = 88

[lint]
ignore = [
  # pydocstyle: Missing Docstrings
  "D1"
]
select = [
  # pyflakes
  "F",
  # pycodestyle
  "E",
  "W",
  # isort
  "I",
  # pydocstyle
  "D"
]

[lint.pycodestyle]
max-line-length = 110

[lint.pydocstyle]
convention = "numpy"
