name: 📓 Notebook Permalink Request
description: Request a notebook permalink.
labels: [notebook]
body:
- type: dropdown
  id: data-type
  attributes:
    label: Data Type
    description: Choose the data type.
    multiple: false
    options:
    - Climate Projection
    - In Situ
    - Reanalyses
    - Satellite_ECVs
    - Seasonal_Forecasts
  validations:
    required: true

- type: dropdown
  id: assessment-category
  attributes:
    label: Assessment Category
    description: Choose the CIM quality assessment category.
    multiple: false
    options:
    - Climate And Weather Extremes
    - Climate Impact Indicators
    - Climate Monitoring
    - Consistency Assessment
    - Data Completeness
    - Forecast Skill
    - Intercomparison
    - Mean
    - Model Performance
    - Trend Assessment
    - Uncertainty
    - Variability
  validations:
    required: true

- type: input
  id: dataset-name
  attributes:
    label: Dataset Name
    description: Provide the ID of the dataset in the catalogue.
    placeholder: e.g., reanalysis-era5-single-levels
  validations:
    required: true

- type: input
  id: question-number
  attributes:
    label: Question Number
    description: Provide the user question number.
    placeholder: e.g., 1
  validations:
    required: true

- type: input
  id: task-id
  attributes:
    label: Task ID
    description: Provide the task ID.
    placeholder: e.g., 1123e4567-e89b-12d3-a456-426655440000
  validations:
    required: true

- type: textarea
  id: notebook-zip
  attributes:
    label: Zipped Notebook
    description: Attach the notebook in zip format.
  validations:
    required: true

- type: textarea
  id: environment
  attributes:
    label: Environment
    description: >
      Paste the output of `conda list` between the `<details>` tags,
      leaving an empty line following the opening tag.

      `conda list` must be executed in the same environment used to run the notebook.
    value: |
      <details>



      </details>
  validations:
    required: true

- type: textarea
  id: extra
  attributes:
    label: Anything else we need to know?
    description: Describe any other information you want to share.
  validations:
    required: true
