name: on-push

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -l {0}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1

  build-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Get changed notebooks
      id: changed-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          **.ipynb
    - name: Checkout book repo
      uses: actions/checkout@v4
      with:
        repository: ecmwf-projects/c3s_eqc_book_main
        path: book
    - name: Install jupyter-book
      run: |
        python -m pip install jupyter-book
    - name: Build pages
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |-
        cd book/c3s_eqc_quality_assessments || exit
        mkdir wip || exit
        for file in ${ALL_CHANGED_FILES}; do
            cp ../../"$file" wip/. || exit
        done
        mkdir ../../pages || exit
        for file in wip/*.ipynb; do
            jupyter-book build "$file" || exit
            prefix=$(basename "$file")
            mv _build/_page/wip-"$prefix"/html ../../pages/"$prefix" || exit
        done
    - uses: actions/upload-artifact@v4
      with:
        path: pages/*
